name: Build and deploy Nuxt 3 app to Azure Web App - NuxtCargo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt 3 app
        run: npm run build

      - name: Upload .output directory
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-output
          path: .output/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download .output artifact
        uses: actions/download-artifact@v4
        with:
          name: nuxt-output
          path: .output

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_87FF2FAB7A2E4777A79F747CCB295CD4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_176EAC83453044A5ABFFD9CE5E820963 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5A2330BB85C7485C95B5EC95C28A08B0 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'NuxtCargo'
          slot-name: 'Production'
          package: .output
